ALTER TABLE `users`
  ADD  `civilite` tinyint(1) NOT NULL DEFAULT '0' AFTER `modified`,
  ADD  `telephone_portable` varchar(255) DEFAULT NULL AFTER `civilite`,
  ADD  `telephone_fixe` varchar(255) DEFAULT NULL AFTER `telephone_portable`,
  ADD  `country_id` int(11) DEFAULT NULL AFTER `telephone_fixe`,
  ADD  `date_naissance` date DEFAULT NULL AFTER `country_id`,
  ADD  `info_a_savoir` text AFTER `date_naissance`,
  ADD  `mode_renumeration` text AFTER `info_a_savoir`,
  ADD  `is_vehicule` tinyint(1) DEFAULT NULL AFTER `mode_renumeration`,
  ADD  `modele_vehicule` varchar(255) DEFAULT NULL AFTER `is_vehicule`,
  ADD  `nbr_borne_transportable_vehicule` int(11) DEFAULT NULL AFTER `modele_vehicule`,
  ADD  `commentaire_vehicule` text AFTER `nbr_borne_transportable_vehicule`,
  ADD  `photo_nom` varchar(45) DEFAULT NULL AFTER `commentaire_vehicule`,
  ADD  `situation_id` int(11) DEFAULT NULL AFTER `photo_nom`,
  ADD  `statut_id` int(11) NOT NULL AFTER `situation_id`,
  ADD  `description_rapide` text AFTER `statut_id`,
  ADD  `vehicule` varchar(255) DEFAULT NULL AFTER `description_rapide`,
  ADD  `capacite_chargement_borne` varchar(255) DEFAULT NULL AFTER `vehicule`,
  ADD  `creneaux_disponibilite` varchar(255) DEFAULT NULL AFTER `capacite_chargement_borne`,
  ADD  `zone_intervention` varchar(255) DEFAULT NULL AFTER `creneaux_disponibilite`,
  ADD  `fonction` varchar(255) DEFAULT NULL AFTER `zone_intervention`,
  ADD  `adresse` varchar(255) DEFAULT NULL AFTER `fonction`,
  ADD  `cp` varchar(255) DEFAULT NULL AFTER `adresse`,
  ADD  `ville` varchar(255) DEFAULT NULL AFTER `cp`,
  ADD  `pays` varchar(255) DEFAULT NULL AFTER `ville`,
  ADD  `commentaire_interne` text AFTER `pays`;